//xss攻击白名单列表
export const options = {
  whiteList: {
    h1: ['style'],
    h2: ['style'],
    h3: ['style'],
    h4: ['style'],
    h5: ['style'],
    h6: ['style'],
    hr: ['style'],
    span: ['style'],
    strong: ['style'],
    b: ['style'],
    i: ['style'],
    br: [],
    p: ['style'],
    pre: ['style'],
    code: ['style'],
    a: ['style', 'target', 'href', 'title', 'rel'],
    img: ['style', 'src', 'title','width','height'],
    div: ['style'],
    table: ['style', 'width', 'border', 'height', 'cellspacing', 'cellpadding'],
    tr: ['style', 'valign', 'align'],
    td: ['style', 'width', 'colspan', 'rowspan', 'border', 'valign', 'align'],
    th: ['style', 'width', 'colspan', 'rowspan', 'border', 'valign', 'align'],
    // update-begin--author:liaozhiyang---date:20260807---for:【LHZP-1128】修复thead标签没解析出来
    thead: ['style'],
    tfoot: ['style'],
    // update-end--author:liaozhiyang---date:20260807---for:【LHZP-1128】修复thead标签没解析出来
    tbody: ['style'],
    ul: ['style'],
    li: ['style'],
    ol: ['style'],
    dl: ['style'],
    dt: ['style'],
    em: ['style'],
    cite: ['style'],
    section: ['style'],
    header: ['style'],
    footer: ['style'],
    blockquote: ['style'],
    audio: ['autoplay', 'controls', 'loop', 'preload', 'src'],
    video: ['autoplay', 'controls', 'loop', 'preload', 'src', 'height', 'width'],
  },
};
