CREATE TABLE IF NOT EXISTS `biz_roomops_machine_room` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `room_id` varchar(64) NOT NULL COMMENT '机房编号',
  `room_name` varchar(100) NOT NULL COMMENT '机房名称',
  `domain_code` varchar(50) NOT NULL DEFAULT 'core_network' COMMENT '专业编码',
  `domain_short_code` varchar(20) NOT NULL DEFAULT 'CORE' COMMENT '专业编号简写',
  `domain_name` varchar(100) NOT NULL DEFAULT '核心网' COMMENT '专业名称',
  `region_code` varchar(50) NOT NULL DEFAULT 'TY' COMMENT '地市编码',
  `region_name` varchar(100) NOT NULL DEFAULT '太原' COMMENT '地市名称',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `status` varchar(20) DEFAULT '1' COMMENT '状态',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `sys_org_code` varchar(64) DEFAULT NULL COMMENT '所属部门',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_roomops_machine_room_room_id` (`room_id`),
  KEY `idx_biz_roomops_machine_room_domain_region` (`domain_code`, `region_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='机房运维-机房基础信息';

CREATE TABLE IF NOT EXISTS `biz_roomops_record` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `record_id` varchar(64) NOT NULL COMMENT '业务记录编号',
  `business_type` varchar(32) NOT NULL COMMENT '业务类型: inspection/fault/engineering',
  `domain_code` varchar(50) NOT NULL DEFAULT 'core_network' COMMENT '专业编码',
  `domain_short_code` varchar(20) NOT NULL DEFAULT 'CORE' COMMENT '专业编号简写',
  `domain_name` varchar(100) NOT NULL DEFAULT '核心网' COMMENT '专业名称',
  `region_code` varchar(50) NOT NULL DEFAULT 'TY' COMMENT '地市编码',
  `region_name` varchar(100) NOT NULL DEFAULT '太原' COMMENT '地市名称',
  `room_id` varchar(64) DEFAULT NULL COMMENT '机房编号',
  `room_name` varchar(100) DEFAULT NULL COMMENT '机房名称',
  `inspector_name` varchar(100) DEFAULT NULL COMMENT '人员名称',
  `dingtalk_userid` varchar(100) DEFAULT NULL COMMENT '钉钉用户ID',
  `dingtalk_unionid` varchar(100) DEFAULT NULL COMMENT '钉钉UnionId',
  `latitude` decimal(18,12) DEFAULT NULL COMMENT '纬度',
  `longitude` decimal(18,12) DEFAULT NULL COMMENT '经度',
  `accuracy` decimal(18,6) DEFAULT NULL COMMENT '定位精度',
  `captured_at` datetime DEFAULT NULL COMMENT '现场采集时间',
  `submitted_at` datetime DEFAULT NULL COMMENT '提交时间',
  `environment_status` varchar(50) DEFAULT NULL COMMENT '环境状态',
  `device_status` varchar(50) DEFAULT NULL COMMENT '设备状态',
  `exception_desc` varchar(1000) DEFAULT NULL COMMENT '异常描述',
  `upload_mode` varchar(32) DEFAULT NULL COMMENT '上传方式: direct/offline_retry',
  `source` varchar(32) DEFAULT NULL COMMENT '来源系统',
  `fault_order_no` varchar(100) DEFAULT NULL COMMENT '故障工单号',
  `handling_result` varchar(1000) DEFAULT NULL COMMENT '处理情况',
  `construction_content` varchar(1000) DEFAULT NULL COMMENT '施工内容',
  `site_problems` varchar(1000) DEFAULT NULL COMMENT '现场发现的问题',
  `remaining_issues` varchar(1000) DEFAULT NULL COMMENT '遗留问题',
  `remark_note` varchar(1000) DEFAULT NULL COMMENT '备注说明',
  `raw_form_json` longtext COMMENT '原始表单JSON',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `sys_org_code` varchar(64) DEFAULT NULL COMMENT '所属部门',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_roomops_record_record_id` (`record_id`),
  KEY `idx_biz_roomops_record_business_type` (`business_type`),
  KEY `idx_biz_roomops_record_domain_region` (`domain_code`, `region_code`),
  KEY `idx_biz_roomops_record_room_id` (`room_id`),
  KEY `idx_biz_roomops_record_submitted_at` (`submitted_at`),
  KEY `idx_biz_roomops_record_fault_order_no` (`fault_order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='机房运维-业务主记录';

CREATE TABLE IF NOT EXISTS `biz_roomops_photo` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `record_id` varchar(64) NOT NULL COMMENT '业务记录编号',
  `photo_index` int NOT NULL COMMENT '照片序号',
  `photo_total` int DEFAULT NULL COMMENT '照片总数',
  `original_filename` varchar(255) DEFAULT NULL COMMENT '原始文件名',
  `stored_filename` varchar(255) DEFAULT NULL COMMENT '存储文件名',
  `storage_path` varchar(500) DEFAULT NULL COMMENT '存储路径',
  `content_type` varchar(100) DEFAULT NULL COMMENT '文件类型',
  `file_size` bigint DEFAULT NULL COMMENT '文件大小',
  `photo_captured_at` datetime DEFAULT NULL COMMENT '照片采集时间',
  `photo_latitude` decimal(18,12) DEFAULT NULL COMMENT '照片纬度',
  `photo_longitude` decimal(18,12) DEFAULT NULL COMMENT '照片经度',
  `photo_accuracy` decimal(18,6) DEFAULT NULL COMMENT '照片定位精度',
  `photo_remark` varchar(500) DEFAULT NULL COMMENT '照片备注',
  `watermarked` tinyint(1) DEFAULT '0' COMMENT '是否加水印',
  `uploaded_at` datetime DEFAULT NULL COMMENT '上传时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `sys_org_code` varchar(64) DEFAULT NULL COMMENT '所属部门',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_roomops_photo_record_index` (`record_id`, `photo_index`),
  KEY `idx_biz_roomops_photo_record_id` (`record_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='机房运维-照片明细';

CREATE TABLE IF NOT EXISTS `biz_roomops_dingtalk_user` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `dingtalk_userid` varchar(100) NOT NULL COMMENT '钉钉用户ID',
  `dingtalk_unionid` varchar(100) DEFAULT NULL COMMENT '钉钉UnionId',
  `name` varchar(100) NOT NULL COMMENT '用户姓名',
  `mobile` varchar(50) DEFAULT NULL COMMENT '手机号',
  `avatar` varchar(500) DEFAULT NULL COMMENT '头像',
  `dept_id` varchar(100) DEFAULT NULL COMMENT '钉钉部门ID',
  `dept_name` varchar(200) DEFAULT NULL COMMENT '部门名称',
  `default_domain_code` varchar(50) NOT NULL DEFAULT 'core_network' COMMENT '默认专业编码',
  `default_domain_short_code` varchar(20) NOT NULL DEFAULT 'CORE' COMMENT '默认专业编号简写',
  `default_domain_name` varchar(100) NOT NULL DEFAULT '核心网' COMMENT '默认专业名称',
  `default_region_code` varchar(50) NOT NULL DEFAULT 'TY' COMMENT '默认地市编码',
  `default_region_name` varchar(100) NOT NULL DEFAULT '太原' COMMENT '默认地市名称',
  `active` varchar(20) DEFAULT '1' COMMENT '是否有效',
  `dingtalk_synced` tinyint(1) DEFAULT '0' COMMENT '是否来自钉钉通讯录同步',
  `last_login_time` datetime DEFAULT NULL COMMENT '最近登录时间',
  `last_sync_time` datetime DEFAULT NULL COMMENT '最近同步时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `sys_org_code` varchar(64) DEFAULT NULL COMMENT '所属部门',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_roomops_dingtalk_user_userid` (`dingtalk_userid`),
  KEY `idx_biz_roomops_dingtalk_user_unionid` (`dingtalk_unionid`),
  KEY `idx_biz_roomops_dingtalk_user_default_scope` (`default_domain_code`, `default_region_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='机房运维-钉钉用户';

CREATE TABLE IF NOT EXISTS `biz_roomops_sync_log` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `sync_batch_id` varchar(64) NOT NULL COMMENT '同步批次号',
  `source_record_id` varchar(64) DEFAULT NULL COMMENT 'VPS前置记录编号',
  `record_id` varchar(64) DEFAULT NULL COMMENT '正式业务记录编号',
  `business_type` varchar(32) DEFAULT NULL COMMENT '业务类型',
  `sync_direction` varchar(32) NOT NULL DEFAULT 'vps_to_jeecg' COMMENT '同步方向',
  `sync_status` varchar(32) NOT NULL DEFAULT 'pending' COMMENT '同步状态',
  `retry_count` int DEFAULT '0' COMMENT '重试次数',
  `error_message` varchar(2000) DEFAULT NULL COMMENT '错误信息',
  `started_at` datetime DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '完成时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `sys_org_code` varchar(64) DEFAULT NULL COMMENT '所属部门',
  PRIMARY KEY (`id`),
  KEY `idx_biz_roomops_sync_log_batch` (`sync_batch_id`),
  KEY `idx_biz_roomops_sync_log_record` (`record_id`),
  KEY `idx_biz_roomops_sync_log_status` (`sync_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='机房运维-同步日志';

CREATE TABLE IF NOT EXISTS `biz_roomops_task` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `task_id` varchar(100) NOT NULL COMMENT '任务编号',
  `business_type` varchar(32) NOT NULL COMMENT '业务类型: inspection/fault/engineering',
  `task_title` varchar(200) DEFAULT NULL COMMENT '任务标题',
  `task_content` varchar(2000) DEFAULT NULL COMMENT '任务内容',
  `domain_code` varchar(50) NOT NULL DEFAULT 'core_network' COMMENT '专业编码',
  `domain_short_code` varchar(20) NOT NULL DEFAULT 'CORE' COMMENT '专业编号简写',
  `domain_name` varchar(100) NOT NULL DEFAULT '核心网' COMMENT '专业名称',
  `region_code` varchar(50) NOT NULL DEFAULT 'TY' COMMENT '地市编码',
  `region_name` varchar(100) NOT NULL DEFAULT '太原' COMMENT '地市名称',
  `room_id` varchar(64) DEFAULT NULL COMMENT '机房编号',
  `room_name` varchar(100) DEFAULT NULL COMMENT '机房名称',
  `assigner_userid` varchar(100) DEFAULT NULL COMMENT '派单人钉钉用户ID',
  `assigner_name` varchar(100) DEFAULT NULL COMMENT '派单人姓名',
  `assignee_userid` varchar(100) DEFAULT NULL COMMENT '执行人钉钉用户ID',
  `assignee_name` varchar(100) DEFAULT NULL COMMENT '执行人姓名',
  `status` varchar(32) NOT NULL DEFAULT 'AVAILABLE' COMMENT '状态: AVAILABLE/ASSIGNED/SUBMITTED/REOPENED/DONE',
  `priority` varchar(20) NOT NULL DEFAULT 'normal' COMMENT '优先级: low/normal/high/urgent',
  `round_count` int NOT NULL DEFAULT '1' COMMENT '当前轮次',
  `deadline_at` datetime DEFAULT NULL COMMENT '截止时间',
  `assigned_at` datetime DEFAULT NULL COMMENT '派单时间',
  `claimed_at` datetime DEFAULT NULL COMMENT '接单时间',
  `submitted_at` datetime DEFAULT NULL COMMENT '提交时间',
  `confirmed_at` datetime DEFAULT NULL COMMENT '确认闭环时间',
  `reject_remark` varchar(1000) DEFAULT NULL COMMENT '驳回备注',
  `confirm_remark` varchar(1000) DEFAULT NULL COMMENT '确认备注',
  `confirm_by` varchar(100) DEFAULT NULL COMMENT '确认人',
  `confirm_userid` varchar(100) DEFAULT NULL COMMENT '确认人用户ID',
  `record_id` varchar(100) DEFAULT NULL COMMENT '关联业务记录编号',
  `project_id` varchar(100) DEFAULT NULL COMMENT '关联工程编号',
  `archived` tinyint NOT NULL DEFAULT '0' COMMENT '是否归档: 0/1',
  `archived_at` datetime DEFAULT NULL COMMENT '归档时间',
  `archived_by` varchar(100) DEFAULT NULL COMMENT '归档人',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `sys_org_code` varchar(64) DEFAULT NULL COMMENT '所属部门',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_biz_roomops_task_task_id` (`task_id`),
  KEY `idx_biz_roomops_task_business_type` (`business_type`),
  KEY `idx_biz_roomops_task_status` (`status`),
  KEY `idx_biz_roomops_task_assignee` (`assignee_userid`),
  KEY `idx_biz_roomops_task_room_id` (`room_id`),
  KEY `idx_biz_roomops_task_project_id` (`project_id`),
  KEY `idx_biz_roomops_task_archived` (`archived`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='机房运维-任务分派主表';

CREATE TABLE IF NOT EXISTS `biz_roomops_task_round` (
  `id` varchar(32) NOT NULL COMMENT '主键',
  `task_id` varchar(100) NOT NULL COMMENT '任务编号',
  `round_no` int NOT NULL DEFAULT '1' COMMENT '轮次',
  `action` varchar(32) NOT NULL COMMENT '动作: CREATE/UPDATE/REASSIGN/CLAIM/SUBMIT/REJECT/CONFIRM',
  `from_status` varchar(32) DEFAULT NULL COMMENT '原状态',
  `to_status` varchar(32) DEFAULT NULL COMMENT '新状态',
  `operator_userid` varchar(100) DEFAULT NULL COMMENT '操作人用户ID',
  `operator_name` varchar(100) DEFAULT NULL COMMENT '操作人姓名',
  `remark` varchar(1000) DEFAULT NULL COMMENT '备注',
  `action_time` datetime DEFAULT NULL COMMENT '操作时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_biz_roomops_task_round_task` (`task_id`, `round_no`),
  KEY `idx_biz_roomops_task_round_action` (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='机房运维-任务流转记录';
