logging:
  level:
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR
    
spring:
  main:
    # 启动加速 (建议开发环境)
    lazy-initialization: true
  application:
    name: jeecg-system
  config:
    import: optional:classpath:config/application-liteflow.yml
  profiles:
    active: '@profile.name@'